# Generated by Django 5.2.8 on 2025-11-14 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 0, 56, 43, 772794)),
        ),
        migrations.AlterField(
            model_name='tasklike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 0, 56, 43, 773326)),
        ),
    ]
