# Generated by Django 5.2.8 on 2025-11-14 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_created_at_alter_tasklike_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 1, 1, 11, 48691)),
        ),
        migrations.AlterField(
            model_name='tasklike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 1, 1, 11, 49191)),
        ),
    ]
