# Generated by Django 5.2.8 on 2025-11-14 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_created_at_alter_tasklike_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 3, 31, 54, 362995)),
        ),
        migrations.AlterField(
            model_name='tasklike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 3, 31, 54, 363517)),
        ),
    ]
