# Generated by Django 5.2.8 on 2025-11-14 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_created_at_alter_tasklike_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 3, 52, 38, 759889)),
        ),
        migrations.AlterField(
            model_name='tasklike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 3, 52, 38, 760283)),
        ),
    ]
