# Generated by Django 5.2.8 on 2025-11-15 04:13

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_created_at_alter_tasklike_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 4, 13, 59, 294142)),
        ),
        migrations.AlterField(
            model_name='tasklike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 4, 13, 59, 294658)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('TASK_CREATED', 'Task Criada'), ('TASK_UPDATED', 'Task Atualizada'), ('SYSTEM', 'Sistema'), ('INFO', 'Informativo'), ('WARNING', 'Aviso'), ('ERROR', 'Erro')], default='INFO', max_length=30)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 15, 4, 13, 59, 295170))),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read'], name='task_notifi_user_id_e74ec3_idx')],
            },
        ),
    ]
