# Generated by Django 5.2.8 on 2025-11-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_created_at_alter_tasklike_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasklike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
