# Generated by Django 5.2.8 on 2025-11-17 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_notification_created_at_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklike',
            name='id',
        ),
        migrations.AddField(
            model_name='tasklike',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
